name: anecdotfun
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^3.0.1
  lottie: ^3.1.0
  nfc_manager: ^3.5.0
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.16
  flutter_launcher_icons: ^0.14.2
  wakelock_plus: ^1.2.8
  collection: ^1.18.0
  logger: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/animations/
    - assets/images/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_square.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_square.png"
  web:
    generate: true
    image_path:  "assets/images/logo_square.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path:  "assets/images/logo_square.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path:  "assets/images/logo_square.png"